defaultDriverPath=/Applications/STISC/MoldSign/native_lib
driver_lib=opensc-pkcs11.so|libcastle.1.0.0.dylib|libbit4xpki.dylib|libeToken.dylib
http_proxy_use=false
http_proxy_port=
http_proxy_url=
use_mscsp=false
